AppDevGCD0805/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppDevGCD0805.Models
{
	public class Category
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public ICollection<Course> Courses { get; set; }
	}
}

AppDevGCD0805/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AppDevGCD0805.Models
{
	public class Course
	{
		
		public int Id { get; set; }
		public string Name { get; set; }

		public string Description { get; set; }
		public int CategoryId { get; set; }
		public Category Category { get; set; }
	}
}

AppDevGCD0805/Models/ErrorViewModel.cs
using System;

namespace AppDevGCD0805.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

AppDevGCD0805/Models/User.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppDevGCD0805.Models
{
	public class User : IdentityUser
	{
		public string FullName { get; set; }
		public int Age { get; set; }

		
	}
}

AppDevGCD0805/Controllers/CategoriesController.cs
using AppDevGCD0805.Data;
using AppDevGCD0805.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppDevGCD0805.Controllers
{
	public class CategoriesController : Controller
	{
		private ApplicationDbContext _db;
		public CategoriesController(ApplicationDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{

			return View(_db.Categories.ToList());
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Category category)
		{
			_db.Categories.Add(category);
			_db.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Delete(int Id)
		{
			var categoryinDb = _db.Categories.SingleOrDefault(item => item.Id == Id);
			_db.Categories.Remove(categoryinDb);
			_db.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{

			var todoInDb = _db.Categories
			  .SingleOrDefault(t => t.Id == id );
			
			return View(todoInDb);
		}

		[HttpPost]
		public ActionResult Edit(Category category)
		{
			var categoryinDb = _db.Categories.SingleOrDefault(item => item.Id == category.Id);
			categoryinDb.Name = category.Name;
			categoryinDb.Description = category.Description;

			_db.SaveChanges();

			return RedirectToAction("Index");
		}

	}
}

AppDevGCD0805/Controllers/CoursesController.cs
using System.Collections.Generic;
using System.Linq;
using AppDevGCD0805.Data;
using AppDevGCD0805.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppDevGCD0805.Controllers
{
    public class CoursesController : Controller
    {
        private ApplicationDbContext _db;
        public CoursesController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        

        public ActionResult Index()
        {
            var model = _db.Courses.Include(x => x.Category);
            return View(model);
        }
        
        [HttpGet]
        
        public IActionResult Create()
        {
            return View();
        }
        
        
        [HttpPost]
        public IActionResult Create(Course course)
        {
            _db.Courses.Add(course);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var courseinDb = _db.Courses.SingleOrDefault(item => item.Id == Id);
            _db.Courses.Remove(courseinDb);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            var todoInDb = _db.Courses
                .SingleOrDefault(t => t.Id == id );
			
            return View(todoInDb);
        }

        [HttpPost]
        public ActionResult Edit(Course course)
        {
            var courseinDb = _db.Courses.SingleOrDefault(item => item.Id == course.Id);
            courseinDb.Name = course.Name;
            courseinDb.Description = course.Description;
            courseinDb.CategoryId = course.CategoryId;

            _db.SaveChanges();

            return RedirectToAction("Index");
        }

      
   }
}

AppDevGCD0805/Controllers/HomeController.cs
using AppDevGCD0805.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AppDevGCD0805.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

AppDevGCD0805/Views/Categories/Create.cshtml
@model AppDevGCD0805.Models.Category



<h1>Create</h1>

<form asp-controller="Categories" asp-action="Create" method="post">
    <div class="form-group">
        <label>Name of category</label>
        <input type="text" class="form-control" placeholder="Input name" asp-for="Name">
    </div>
    <div class="form-group">
        <label>Description</label>
        <input type="text" class="form-control" placeholder="Description input" asp-for="Description">
    </div>
    <button type="submit" class="btn btn-outline-success">Create</button>
</form>

AppDevGCD0805/Views/Categories/Edit.cshtml
@model AppDevGCD0805.Models.Category



<h1>Edit</h1>
<form asp-controller="Categories" asp-action="Edit" method="post">
    <div class="form-group">
        <label>Name of category</label>
        <input type="text" class="form-control" placeholder="Input name" asp-for="Name">
    </div>
    <div class="form-group">
        <label>Description</label>
        <input type="text" class="form-control" placeholder="Description input" asp-for="Description">
    </div>
    <button type="submit" class="btn btn-outline-success">Edit</button>
</form>

AppDevGCD0805/Views/Categories/Index.cshtml
@model IEnumerable<AppDevGCD0805.Models.Category>

<h1>Category</h1>
<main>
    
    <br>

    <a class="nav-link  btn btn-outline-success col-1" asp-area="" asp-controller="Categories" asp-action="Create">Create</a>

    <br>
    <table class="table">
        <thead class="thead-dark">
            <tr>
          
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Acction</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", "Categories", new { Id = item.Id }, new { @class = " btn btn-outline-danger " })
                        @Html.ActionLink("Edit", "Edit", "Categories", new { id = item.Id }, new { @class = " btn btn-outline-info " })
                        @* @Html.ActionLink("Details", "Details", "Todos", new { id = item.Id }, new { @class = "btn btn-info" }) *@
                    </td>
                </tr>
            }
        </tbody>
    </table>
</main>

AppDevGCD0805/Views/Courses/Create.cshtml
@model AppDevGCD0805.Models.Course



<h1>CreateCourse</h1>
<form asp-controller="Courses" asp-action="Create" method="post">
  <div class="form-group">
    <label>Name of course</label>
    <input type="text" class="form-control" placeholder="Input name" asp-for="Name">
  </div>
  <div class="form-group">
    <label>Description</label>
    <input type="text" class="form-control" placeholder="Description input" asp-for="Description">
  </div>
  <div class="form-group">
    <label>CategoryId</label>
    <input type="text" class="form-control" placeholder="CategoryId input" asp-for="CategoryId">
  </div>
  <button type="submit" class="btn btn-outline-success">Create</button>
</form>

AppDevGCD0805/Views/Courses/Edit.cshtml
@model AppDevGCD0805.Models.Course



<h1>Edit</h1>
<form asp-controller="Courses" asp-action="Edit" method="post">

  <div class="form-group">
    <label>Name of Course</label>
    <input type="text" class="form-control" placeholder="Input name" asp-for="Name">
  </div>
  <div class="form-group">
    <label>Description</label>
    <input type="text" class="form-control" placeholder="Description input" asp-for="Description">
  </div>
  <div class="form-group">
    <label>Description</label>
    <input type="text" class="form-control" placeholder="Description input" asp-for="CategoryId">
  </div>
  <button type="submit" class="btn btn-outline-success">Edit</button>
</form>

AppDevGCD0805/Views/Courses/Index.cshtml
@model IEnumerable<AppDevGCD0805.Models.Course>

<h1>COURSE</h1>

<main>

  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  <br>

  <a class="nav-link  btn btn-outline-success col-1" asp-area="" asp-controller="Courses" asp-action="Create">Create</a>

  <br>
  <table class="table">
    <thead class="thead-dark">
      <tr>

        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Category</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
        <tr>
          <th scope="row">@item.Name</th>
          <td>@item.Description</td>
          <td>@item.Category.Name</td>

          <td>
            @Html.ActionLink("Delete", "Delete", "Courses", new { Id = item.Id }, new { @class = "btn btn-outline-danger" })
            @Html.ActionLink("Edit", "Edit", "Courses", new { id = item.Id }, new { @class = "btn btn-outline-info" })
            @* @Html.ActionLink("Details", "Details", "Todos", new { id = item.Id }, new { @class = "btn btn-info" }) *@
          </td>
        </tr>
      }

    </tbody>
  </table>
</main>

AppDevGCD0805/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppDevGCD0805/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppDevGCD0805</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppDevGCD0805</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AppDevGCD0805 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>